// Code generated by "stringer -type Instruction"; DO NOT EDIT.

package instructions

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpConstant-0]
	_ = x[OpAdd-1]
	_ = x[OpMinus-2]
	_ = x[OpMul-3]
	_ = x[OpDiv-4]
	_ = x[OpReturn-5]
}

const _Instruction_name = "OpConstantOpAddOpMinusOpMulOpDivOpReturn"

var _Instruction_index = [...]uint8{0, 10, 15, 22, 27, 32, 40}

func (i Instruction) String() string {
	if i < 0 || i >= Instruction(len(_Instruction_index)-1) {
		return "Instruction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Instruction_name[_Instruction_index[i]:_Instruction_index[i+1]]
}
