// Code generated by "stringer -type Instruction"; DO NOT EDIT.

package bytecode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpConst-0]
	_ = x[OpLoad-1]
	_ = x[OpAdd-2]
	_ = x[OpMinus-3]
	_ = x[OpMul-4]
	_ = x[OpDiv-5]
	_ = x[OpFloorDiv-6]
	_ = x[OpAnd-7]
	_ = x[OpMod-8]
	_ = x[OpLt-9]
	_ = x[OpGt-10]
	_ = x[OpGe-11]
	_ = x[OpLe-12]
	_ = x[OpEq-13]
	_ = x[OpNe-14]
	_ = x[OpUnaryNot-15]
	_ = x[OpUnaryPlus-16]
	_ = x[OpUnaryMinus-17]
	_ = x[OpReturn-18]
	_ = x[OpCall-19]
	_ = x[OpLoadAttr-20]
	_ = x[OpBr-21]
	_ = x[OpBrIf-22]
	_ = x[OpBrIfOrPop-23]
	_ = x[OpBrIfFalseOrPop-24]
}

const _Instruction_name = "OpConstOpLoadOpAddOpMinusOpMulOpDivOpFloorDivOpAndOpModOpLtOpGtOpGeOpLeOpEqOpNeOpUnaryNotOpUnaryPlusOpUnaryMinusOpReturnOpCallOpLoadAttrOpBrOpBrIfOpBrIfOrPopOpBrIfFalseOrPop"

var _Instruction_index = [...]uint8{0, 7, 13, 18, 25, 30, 35, 45, 50, 55, 59, 63, 67, 71, 75, 79, 89, 100, 112, 120, 126, 136, 140, 146, 157, 173}

func (i Instruction) String() string {
	if i < 0 || i >= Instruction(len(_Instruction_index)-1) {
		return "Instruction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Instruction_name[_Instruction_index[i]:_Instruction_index[i+1]]
}
