// Code generated by "stringer -type Instruction"; DO NOT EDIT.

package bytecode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpConst-0]
	_ = x[OpLoad-1]
	_ = x[OpAdd-2]
	_ = x[OpMinus-3]
	_ = x[OpMul-4]
	_ = x[OpDiv-5]
	_ = x[OpAnd-6]
	_ = x[OpReturn-7]
	_ = x[OpBr-8]
	_ = x[OpBrIf-9]
	_ = x[OpBrIfOrPop-10]
	_ = x[OpBrIfFalseOrPop-11]
}

const _Instruction_name = "OpConstOpLoadOpAddOpMinusOpMulOpDivOpAndOpReturnOpBrOpBrIfOpBrIfOrPopOpBrIfFalseOrPop"

var _Instruction_index = [...]uint8{0, 7, 13, 18, 25, 30, 35, 40, 48, 52, 58, 69, 85}

func (i Instruction) String() string {
	if i < 0 || i >= Instruction(len(_Instruction_index)-1) {
		return "Instruction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Instruction_name[_Instruction_index[i]:_Instruction_index[i+1]]
}
